# -*- coding: utf-8 -*-

STATUS_CODE={
    'success':{'status':0, 'message':'success'},
    'under_crawl':{'status':1, 'message':'under crawling'},
    'result_exists': {'status':2, 'message': 'result alreay exists'},
    'queue_error':{'status':3000, 'message':'job enqueue error'},
    'crawler_timeout':{'status':3001, 'message':'max retry to get crawler state'},
    'timeout':{'status':4009, 'message':'timeout'},
    'crawler_failed':{'status':3002, 'message':'Cralwer behavior error'},
    'param_timeout':{'status':3003, 'message': u'等待输入参数超时'},
    'param_error':{'status':3004, 'message':'not expected parameter'},
    'json_error':{'status':3005, 'message':'load json error'},
    'xml_error':{'status':3006, 'message':'xml_error'},
    'html_error':{'status':3007, 'message':'html_error'},
    'expected_key_error':{'status':3008, 'message': u'未知数据结构，数据解析失败'},
    'no_query_data':{'status':3009, 'message':'no data exist in your query'},
    'request_error':{'status':5005, 'message':'request error'},
    'data_incomplete':{'status':3097, 'message':'data not complete'},
    'crawl_error':{'status':3098, 'message':'error occurred when crawl'},
    'user_exit':{'status':3099, 'message':'exit by user'},
    'no_supported_crawler':{'status':3100, 'message':'No supported crawler'},
    'login_param_error':{'status':4000, 'message': u'登录失败！手机号、密码或其它参数错误。'},
    'invalid_tel':{'status':4001, 'message': u'手机号错误'},
    'pin_pwd_error':{'status':4002, 'message': u'服务密码错误'},
    'verify_error':{'status':4003, 'message': u'验证码错误'},
    'user_name_error':{'status':4004, 'message': u'姓名错误'},
    'user_id_error':{'status':4005, 'message': u'身份证错误'},
    'real_name_registration_error':{'status':4006, 'message': u'禁止查询：该号码未进行实名认证'},
    'sample_pwd':{'status':4007, 'message': u'服务密码过于简单'},
    'over_max_sms_error':{'status':4010, 'message': u'今日网上营业厅短信下发次数已达上限，请明天再试。'},
    'send_sms_error': {'status':4116, 'message': u'短信发送失败，请稍后重试。'},
    'send_sms_too_quick_error': {'status': 4999, 'message': u'网上营业厅提醒您：操作过于频繁，请稍等30分钟后重试。'},
    'reusable_sms': {'status': 4990, 'message': u'上次的短信验证码还在有效期内，请使用上次的短信验证码。'},
    'auto_captcha_code_error': {'status': 4201, 'message': u'图片验证码自动打码失败'},
    'website_busy_error': {'status':4107, 'message': u'网上营业厅网络繁忙，请稍后重试。如有疑问请联系运营商客服电话。'},
    'website_maintaining_error': {'status':4108, 'message': u'网上营业厅系统维护中，请1小时后再试。'},
    'account_locked': {'status':4013, 'message': u'由于密码或验证码输入错误次数过多, 账号已被运营商锁定'},
    'over_query_limit': {'status':5017, 'message': u'尊敬的客户您好，系统检测您的访问过于频繁，为保障您的账户安全请明天再试。'},
    'user_prohibited_error': {'status':5301, 'message': u'采集失败，该用户办理了详单禁查业务。'},
    'websiter_prohibited_error': {'status':5302, 'message': u'运营商禁止查询该月详单，可能是过户前的信息，或者是其它特殊禁查情况'},
    'user_multiple_loggedin_error': {'status':5303, 'message': u'网上营业厅提醒您：您已在别处登录，请重新登录'},
    'invalid_sid':{'status':5000, 'message':'无效的会话'},
    'outdated_sid':{'status':5001, 'message':'会话已超时'},
    'duplicate_sid':{'status':5002, 'message':'duplicate sid'},
    # 'init_sid_info':{'status':5003, 'message':'同一客户多次请求，初始化SID失败'},
    'unknown_error':{'status':9999, 'message':'unknown error'},
    'internal_error':{'status':5555, 'message':'internal error'},
}
